# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Martin's Blog"
description: > # this means to ignore newlines until "email:"
   I am a recent college graduate who graduated with a degree in computer science in December of 2019.
   I have worked with full-stack web applications, data science(solving data problems), site security and testing software.
   I would like to reinforce things I love analyzing or inspire from. It ranges from taking advice to reading books.
   The blog is using Jekyll Mediator theme which is a Medium Inspired theme.

email: simplisticmartin@gmail.com
#blog logo
logo: "/assets/images/favicon.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Martin Li'
author: 'Martin Li'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://simplisticmartin.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@noneset'
linkedin_handle: '@simplisticmartin'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/simplisticmartin
    desc: Connect with me on linkedin
    share_url: 
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/simplisticmartin
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
